// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAA3-OUw-ZlptB8X4Jnj4NV5pqU9NcjKs',
    appId: '1:596152602563:web:ca49d9b46e604588c77776',
    messagingSenderId: '596152602563',
    projectId: 'shopflutter-d3308',
    authDomain: 'shopflutter-d3308.firebaseapp.com',
    storageBucket: 'shopflutter-d3308.firebasestorage.app',
    measurementId: 'G-6MYJ4Q0QZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2U0pEjAfNDruRAOyJmaXJ6v3exDBL8Sw',
    appId: '1:596152602563:android:95fb9ef16adb35c7c77776',
    messagingSenderId: '596152602563',
    projectId: 'shopflutter-d3308',
    storageBucket: 'shopflutter-d3308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUT0JGPk9DP6315svPF5NpaDMNkiSb7Uk',
    appId: '1:596152602563:ios:80c402138281f91bc77776',
    messagingSenderId: '596152602563',
    projectId: 'shopflutter-d3308',
    storageBucket: 'shopflutter-d3308.firebasestorage.app',
    iosBundleId: 'com.example.shopflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUT0JGPk9DP6315svPF5NpaDMNkiSb7Uk',
    appId: '1:596152602563:ios:80c402138281f91bc77776',
    messagingSenderId: '596152602563',
    projectId: 'shopflutter-d3308',
    storageBucket: 'shopflutter-d3308.firebasestorage.app',
    iosBundleId: 'com.example.shopflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAA3-OUw-ZlptB8X4Jnj4NV5pqU9NcjKs',
    appId: '1:596152602563:web:8e58ffe8196e5b36c77776',
    messagingSenderId: '596152602563',
    projectId: 'shopflutter-d3308',
    authDomain: 'shopflutter-d3308.firebaseapp.com',
    storageBucket: 'shopflutter-d3308.firebasestorage.app',
    measurementId: 'G-S4TC8YRPBN',
  );
}
